import Head from 'next/head'
import Image from 'next/image'
import styles from '@/styles/Home.module.css'
import { useState } from 'react'
import { Input } from '@/components/Input'

export default function Home () {
  const [value, setValue] = useState<string>('Name')
  const [valueTwo, setValueTwo] = useState<string>('Commander')
  const [valueThree, setValueThree] = useState<string>('Partner')
  const [valueFour, setValueFour] = useState<string>('Companion')
  
  const [loading, setLoading] = useState<boolean>(false)

  const delay = (ms: number) => new Promise(res => setTimeout(res, ms))

  const getData = async (text: string) => {
    setLoading(true)
    await delay(1000)
    console.log('test', text)
    setLoading(false)
  }

  return (
    <>
      <Head>
        <title>Melee sucks</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main className={styles.main}>



    <div className={styles.playerFormContainer}>
        <Input
          value={value}
          setValue={setValue}
          loading={loading}
          getData={getData}
        />
        <Input
          value={valueTwo}
          setValue={setValueTwo}
          loading={loading}
          getData={getData}
        />
        <Input
          value={valueThree}
          setValue={setValueThree}
          loading={loading}
          getData={getData}
        />
        <Input
          value={valueFour}
          setValue={setValueFour}
          loading={loading}
          getData={getData}
        />
</div>

<div className={styles.playerCard}>
  <div className={styles.playerCardValue}><button>-</button><p>Life Total:</p>40<p></p><button>+</button></div>
  <div className={styles.playerCardValue}><button>-</button><p>Commander Tax:</p>0<p></p><button>+</button></div>
  <div className={styles.playerCardValue}><button>-</button><p>Poison:</p>0<p></p><button>+</button></div>
  <div className={styles.playerCardValue}><button>-</button><p>Storm Count:</p>0<p></p><button>+</button></div>
  <div className={styles.playerCardValue}><button>-</button><p>Commander Damage:</p>0<p></p><button>+</button></div>
</div>
      </main>
    </>
  )
}
